# Generated by Django 5.1.2 on 2024-11-21 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizCreator',
            fields=[
                ('creater_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='QuizDetails1',
            fields=[
                ('quiz_id', models.AutoField(primary_key=True, serialize=False)),
                ('quiz_img', models.ImageField(blank=True, null=True, upload_to='quiz/profile/')),
                ('created_by', models.CharField(max_length=150)),
                ('title_quiz', models.CharField(max_length=150)),
                ('description_quiz', models.TextField(max_length=300)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myquizz.quizcreator')),
            ],
        ),
        migrations.CreateModel(
            name='QuizDetails2',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=300)),
                ('option1', models.CharField(max_length=25)),
                ('option2', models.CharField(max_length=25)),
                ('option3', models.CharField(max_length=25)),
                ('correct_option', models.CharField(max_length=25)),
                ('points', models.IntegerField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myquizz.quizdetails1')),
            ],
        ),
        migrations.CreateModel(
            name='Response1',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(default='example@example.com', max_length=100)),
                ('correct_answer', models.CharField(max_length=300)),
                ('points', models.IntegerField()),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myquizz.quizdetails2')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myquizz.quizdetails1')),
            ],
        ),
    ]
